Provide support for mongodb 3.4 community and enterprise editions
Community edition has to be compiled and it takes ~3 hours to build.

Command respectively are:

./scripts/dbimage-make.sh -i 9.3.89.213 -d mongodb -c -k luke
./scripts/dbimage-make.sh -i 9.3.89.213 -d mongodb -e -k luke

Note you only end up with one datastore definition as the second
invocation overwrites the first.  One has to manually run trove-manage
commands to recreate the datastore for the community edition -- the
1st image produced above.

The code drop fixes a trove problem in the management of users
for mongodb.  Like other databases, users should be expressed as a
single unit, however, that is not the case with Trove mongo support.
It requires that the user be specified relative to a database.  This
results in a single user being listed multiple times if he is
associated with multiple databases.  This does not scale well and is
confusing as each database.user entity can be updated independently
to change the password.  There is only one user and one password.

This commit maintains compatibility with the database.user format
but allows users to be specified independently as long as an
initial database is provided.  The database is created separately,
but importantly the Trove UI now only shows the user once.

There is a Trove restriction in the management of databases.  It is
not possible to create an empty database in Trove.  Mongodb garbage
collects empty databases, so the Trove create database command and
UI does not work properly for mongo as the database does not persist.

To overcome this problem, the database must be created from the client.

1) Create the user in Trove.  For example, user=luke, initial db=spain
2) Create the database from a mongo client

mongo --host 9.3.80.128 --authenticationDatabase spain -u luke -p
- use spain
- db.createCollection("food")
- db.food.insert( { tapas: true } )
- exit

The database spain should be visible in Trove now.

Change-Id: I990b5ea380ee84ceccd64ecf371949e33a5c1b55

diff --git a/osa/dbaas/dbimage-builder/diffs/trove/integration/element-mongodb.patch b/osa/dbaas/dbimage-builder/diffs/trove/integration/element-mongodb.patch
--- a/osa/dbaas/dbimage-builder/diffs/trove/integration/element-mongodb.patch
+++ b/osa/dbaas/dbimage-builder/diffs/trove/integration/element-mongodb.patch
@@ -1,8 +1,8 @@
 diff --git a/integration/scripts/files/elements/ubuntu-mongodb/install.d/20-mongodb b/integration/scripts/files/elements/ubuntu-mongodb/install.d/20-mongodb
-index 4ab5c34..c35ca52 100755
+index 4ab5c34..bf4a5b0 100755
 --- a/integration/scripts/files/elements/ubuntu-mongodb/install.d/20-mongodb
 +++ b/integration/scripts/files/elements/ubuntu-mongodb/install.d/20-mongodb
-@@ -1,8 +1,84 @@
+@@ -1,8 +1,62 @@
 -#!/bin/sh
 +#!/bin/bash
  
@@ -21,17 +21,8 @@ index 4ab5c34..c35ca52 100755
 +ESC_MONGODB_CONF="${MONGODB_CONF//\//\\/}"
 +ESC_MONGOS_CONF="${MONGOS_CONF//\//\\/}"
 +
-+# /var/run -> /run.  Create /run/mongodb as the creation of /var/run/mongodb
-+# is not reflected in the generated image.  Failure may be related to a
-+# missing bind mount in the chroot'd environment
-+mkdir -p /run/mongodb $MONGODB_RUN_DIR
-+
 +if [ "$DIB_MYENTERPRISE_EDITION" == "true" ]; then
-+    apt-get install -y mongodb-enterprise
-+    # mongodb-enterprise package should create mongodb user
-+    chown -R mongodb:mongodb /run/mongodb $MONGODB_RUN_DIR
-+    sed -i "s/ExecStart=.*/ExecStart=\/usr\/bin\/mongod --quiet --config $ESC_MONGODB_CONF/" /lib/systemd/system/mongod.service
-+    systemctl enable mongod.service
++    apt-get install -y $DIB_MYDBPKG
 +    exit 0
 +fi
 +
@@ -56,7 +47,7 @@ index 4ab5c34..c35ca52 100755
 +cd $MONGODB_NAME
 +
 +unset ARCH
-+scons core
++scons --disable-warnings-as-errors core
 +scons --prefix=/usr install
 +export ARCH=$ARCH_SAV
 +
@@ -66,7 +57,6 @@ index 4ab5c34..c35ca52 100755
 +
 +MONGODB_DATA_DIR=/var/lib/mongodb
 +MONGODB_LOG_DIR=/var/log/mongodb
-+MONGODB_RUN_DIR=/var/run/mongodb
 +
 +mkdir -p $MONGODB_DATA_DIR
 +chown -R mongodb:mongodb $MONGODB_DATA_DIR
@@ -74,21 +64,9 @@ index 4ab5c34..c35ca52 100755
 +mkdir -p $MONGODB_LOG_DIR
 +chown -R mongodb:mongodb $MONGODB_LOG_DIR
 +
-+chown -R mongodb:mongodb /run/mongodb $MONGODB_RUN_DIR
-+
-+cp /tmp/$MONGODB_NAME/debian/mongod.service /lib/systemd/system/mongod.service
-+cp /tmp/$MONGODB_NAME/debian/mongod.service /lib/systemd/system/mongos.service
-+
-+sed -i "s/ExecStart=.*/ExecStart=\/usr\/bin\/mongod --quiet --config $ESC_MONGODB_CONF/" /lib/systemd/system/mongod.service
-+
-+sed -i "s/ExecStart=.*/ExecStart=\/usr\/bin\/mongos --quiet --config $ESC_MONGOS_CONF/" /lib/systemd/system/mongos.service
-+
 +# Clean the build tree to minimize the size of the image and to avoid running out of space when creating the image
 +rm /tmp/$MONGODB_NAME.tar.gz
 +rm -rf /tmp/$MONGODB_NAME
-+
-+systemctl enable mongod.service
-+systemctl enable mongos.service
 diff --git a/integration/scripts/files/elements/ubuntu-mongodb/install.d/25-trove-mongo-dep b/integration/scripts/files/elements/ubuntu-mongodb/install.d/25-trove-mongo-dep
 index a8b3ddc..6774019 100755
 --- a/integration/scripts/files/elements/ubuntu-mongodb/install.d/25-trove-mongo-dep
@@ -105,33 +83,64 @@ index a8b3ddc..6774019 100755
 +    apt-get --allow-unauthenticated install -y python-pymongo-doc
 +fi
 diff --git a/integration/scripts/files/elements/ubuntu-mongodb/install.d/30-mongodb-conf b/integration/scripts/files/elements/ubuntu-mongodb/install.d/30-mongodb-conf
-index afb5828..cef03d2 100755
+index afb5828..42cd816 100755
 --- a/integration/scripts/files/elements/ubuntu-mongodb/install.d/30-mongodb-conf
 +++ b/integration/scripts/files/elements/ubuntu-mongodb/install.d/30-mongodb-conf
-@@ -3,10 +3,6 @@
+@@ -1,26 +1,45 @@
+-#!/bin/sh
++#!/bin/bash
+ 
  set -e
  set -o xtrace
  
 -# Remove the default pid file
 -rm -f /var/run/mongodb.pid
--
--
++if [ -e /etc/mongod.conf ]; then
++    cp /etc/mongod.conf /etc/mongod.conf.orig
++fi
+ 
++if [ "$DIB_MYDEBUG" == "true" ]; then
++    DEBUGLEVEL=3                  # Max is 5
++else
++    DEBUGLEVEL=0                  # Default informational
++fi
+ 
  cat > /etc/mongod.conf << '_EOF_'
++processManagement.pidFilePath: /var/run/mongodb/mongodb.pid
  storage.dbPath: /var/lib/mongodb
  security.authorization: enabled
-@@ -17,7 +13,6 @@ systemLog.logAppend: true
+ storage.engine: wiredTiger
+ storage.journal.enabled: true
++systemLog.verbosity: DEBUGLEVEL
++systemLog.component.accessControl.verbosity: 1
+ systemLog.destination: file
+ systemLog.logAppend: true
  systemLog.path: /var/log/mongodb/mongod.log
  _EOF_
  
--
++sed -i "s/DEBUGLEVEL/$DEBUGLEVEL/" /etc/mongod.conf
+ 
++if [ -e /etc/mongos.conf ]; then
++    cp /etc/mongos.conf /etc/mongos.conf.orig
++fi
++
++# TBD.  Mongos is not started.  Will be required for sharded clusters
  cat > /etc/mongos.conf << '_EOF_'
- security.authorization: enabled
+-security.authorization: enabled
++sharding.configDB: clustering/cfg1.example.net:27017
++storage.engine: wiredTiger
  systemLog.destination: file
+ systemLog.logAppend: true
++systemLog.verbosity: DEBUGLEVEL
+ systemLog.path: /var/log/mongodb/mongos.log
+ _EOF_
++
++sed -i "s/DEBUGLEVEL/$DEBUGLEVEL/" /etc/mongos.conf
 diff --git a/integration/scripts/files/elements/ubuntu-mongodb/pre-install.d/10-mongodb-apt-key b/integration/scripts/files/elements/ubuntu-mongodb/pre-install.d/10-mongodb-apt-key
-index 1345f50..4d69fb6 100755
+index 1345f50..59716fd 100755
 --- a/integration/scripts/files/elements/ubuntu-mongodb/pre-install.d/10-mongodb-apt-key
 +++ b/integration/scripts/files/elements/ubuntu-mongodb/pre-install.d/10-mongodb-apt-key
-@@ -1,14 +1,21 @@
+@@ -1,14 +1,28 @@
 -#!/bin/sh
 +#!/bin/bash
  
@@ -152,10 +161,17 @@ index 1345f50..4d69fb6 100755
 +    apt-get --allow-unauthenticated -y install software-properties-common
  
 -echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
-+    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
++    if [ "$DIB_MYDBVERSION" == "3.3" ]; then
++        apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
++    elif [ "$DIB_MYDBVERSION" == "3.4" ]; then
++        apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
++    else
++        echo "ERROR invalid Mongodb Enterprise version $DIB_MYDBVERSION"
++        exit 1
++    fi
  
 -apt-get -y update
-+    echo "deb http://repo.mongodb.com/apt/ubuntu "$(lsb_release -sc)"/mongodb-enterprise/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-enterprise.list
++    echo "deb http://repo.mongodb.com/apt/ubuntu "$(lsb_release -sc)"/mongodb-enterprise/$DIB_MYDBVERSION multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-enterprise.list
 +
 +    apt-get -y update
 +fi
@@ -189,6 +205,101 @@ index 0000000..3229917
 +
 +_EOF_
 +
+diff --git a/integration/scripts/files/elements/ubuntu-xenial-mongodb/install.d/41-mongod-systemd b/integration/scripts/files/elements/ubuntu-xenial-mongodb/install.d/41-mongod-systemd
+new file mode 100755
+index 0000000..db3a6b8
+--- /dev/null
++++ b/integration/scripts/files/elements/ubuntu-xenial-mongodb/install.d/41-mongod-systemd
+@@ -0,0 +1,41 @@
++#!/bin/sh
++
++set -e
++set -o xtrace
++
++cat > /lib/systemd/system/mongod.service << '_EOF_'
++[Unit]
++Description=High-performance, schema-free document-oriented database
++After=network.target
++Documentation=https://docs.mongodb.org/manual
++
++[Service]
++User=mongodb
++Group=mongodb
++RuntimeDirectory=mongodb
++ExecStart=/usr/bin/mongod --config /etc/mongod.conf
++
++# file size
++LimitFSIZE=infinity
++# cpu time
++LimitCPU=infinity
++# virtual memory size
++LimitAS=infinity
++# open files
++LimitNOFILE=64000
++# processes/threads
++LimitNPROC=64000
++# memlock
++LimitMEMLOCK=2000000
++# total threads (user+kernel)
++TasksMax=infinity
++TasksAccounting=false
++
++# Recommended limits for for mongod as specified in
++# http://docs.mongodb.org/manual/reference/ulimit/#recommended-settings
++
++[Install]
++WantedBy=multi-user.target
++_EOF_
++
++systemctl enable mongod.service
+diff --git a/integration/scripts/files/elements/ubuntu-xenial-mongodb/install.d/42-mongos-systemd b/integration/scripts/files/elements/ubuntu-xenial-mongodb/install.d/42-mongos-systemd
+new file mode 100755
+index 0000000..a8d2761
+--- /dev/null
++++ b/integration/scripts/files/elements/ubuntu-xenial-mongodb/install.d/42-mongos-systemd
+@@ -0,0 +1,42 @@
++#!/bin/sh
++
++set -e
++set -o xtrace
++
++cat > /lib/systemd/system/mongos.service << '_EOF_'
++[Unit]
++Description=High-performance, schema-free document-oriented database
++After=network.target
++Documentation=https://docs.mongodb.org/manual
++
++[Service]
++User=mongodb
++Group=mongodb
++RuntimeDirectory=mongodb
++ExecStart=/usr/bin/mongos --config /etc/mongos.conf
++
++# file size
++LimitFSIZE=infinity
++# cpu time
++LimitCPU=infinity
++# virtual memory size
++LimitAS=infinity
++# open files
++LimitNOFILE=64000
++# processes/threads
++LimitNPROC=64000
++# memlock
++LimitMEMLOCK=2000000
++# total threads (user+kernel)
++TasksMax=infinity
++TasksAccounting=false
++
++# Recommended limits for for mongod as specified in
++# http://docs.mongodb.org/manual/reference/ulimit/#recommended-settings
++
++[Install]
++WantedBy=multi-user.target
++_EOF_
++
++# TBD.  Started for sharded clusters
++# systemctl enable mongos.service
 diff --git a/integration/scripts/files/elements/ubuntu-mongodb/install.d/10-mongodb-thp b/integration/scripts/files/elements/ubuntu-mongodb/install.d/10-mongodb-thp
 deleted file mode 100755
 index 48d6c8b..0000000
